import { createContext, useContext, useState } from "react";
import type { ReactNode } from "react";

export type Lang = "es" | "en";

const T = {
  es: {
    // Navegación
    nav_search: "Buscar viajes",
    nav_reservations: "Mis reservas",
    nav_dashboard: "Panel de gestión",
    nav_login: "Ingresar",
    nav_signup: "Crear cuenta",
    nav_settings: "Configuración",
    nav_logout: "Cerrar sesión",
    nav_account: "Mi cuenta",
    // Configuración
    config_title: "Configuración",
    config_appearance: "Apariencia",
    config_dark: "Modo oscuro",
    config_dark_desc: "Cambia la apariencia de la plataforma",
    config_language: "Idioma",
    config_notifications: "Notificaciones",
    config_notif_desc: "Recibir alertas del sistema",
    config_profile: "Perfil",
    config_name: "Nombre completo",
    config_photo: "URL de foto de perfil",
    config_password: "Nueva contraseña",
    config_confirm_password: "Confirmar contraseña",
    config_save: "Guardar",
    config_saving: "Guardando...",
    config_saved: "Cambios guardados ✓",
    config_password_mismatch: "Las contraseñas no coinciden",
    config_name_required: "El nombre es obligatorio",
    // Index — Hero
    hero_badge: "✨ Boletos de bus en línea, Ecuador",
    hero_title: "Viaja seguro y rápido por Ecuador",
    hero_subtitle: "Reserva boletos de bus al instante. Pago seguro, asientos garantizados y boleto digital en tu celular.",
    hero_search_required: "Completa todos los campos para buscar",
    // Index — Buscador
    search_origin: "Origen",
    search_origin_placeholder: "¿De dónde sales?",
    search_destination: "Destino",
    search_destination_placeholder: "¿A dónde vas?",
    search_date: "Fecha",
    search_btn: "Buscar viajes",
    // Index — Beneficios
    benefits_title: "¿Por qué BusEcuador?",
    benefits_subtitle: "Una experiencia de compra moderna pensada para pasajeros y cooperativas.",
    benefit_seat_title: "Selección visual de asiento",
    benefit_seat_desc: "Elige tu lugar exacto en un mapa interactivo del bus.",
    benefit_pay_title: "Pago seguro con validación",
    benefit_pay_desc: "Sube tu comprobante de transferencia y un oficinista lo valida.",
    benefit_qr_title: "Boleto digital con QR",
    benefit_qr_desc: "Lleva tu boleto en el celular y aborda mostrando el QR.",
    benefit_discount_title: "Descuentos legales",
    benefit_discount_desc: "Aplicamos automáticamente menores, tercera edad y discapacidad.",
    benefit_multi_title: "Compra para varios",
    benefit_multi_desc: "Adquiere varios asientos en una sola reserva.",
    benefit_coop_title: "Cooperativas verificadas",
    benefit_coop_desc: "Trabajamos con operadoras autorizadas por la ANT.",
    // Index — CTA
    cta_title: "¿Listo para tu próximo viaje?",
    cta_subtitle: "Crea tu cuenta gratis y empieza a reservar boletos en segundos.",
    cta_signup: "Crear cuenta",
    cta_search: "Buscar viajes",
    // Buscar
    buscar_city: "Ciudad",
    buscar_bus_type: "Tipo de bus",
    buscar_all: "Todos",
    buscar_btn: "Buscar",
    buscar_empty_title: "No encontramos viajes",
    buscar_empty_desc: "Prueba ajustando los filtros o cambia la fecha.",
    buscar_discount_applied: "50% dto. aplicado",
    buscar_select_seats: "Elegir asientos",
    // Compra — etapa asientos
    compra_loading: "Cargando disponibilidad...",
    compra_error: "Error",
    compra_trip_selected: "Viaje seleccionado",
    compra_price_per_seat: "Precio por asiento",
    compra_base_price: "precio base",
    compra_available: "Disponible",
    compra_selected: "Seleccionado",
    compra_occupied: "Ocupado",
    compra_bus_front: "Frente del bus",
    compra_floor1: "Piso 1",
    compra_floor2: "Piso 2 — Premium",
    compra_select_prompt_single: "Selecciona 1 asiento para continuar",
    compra_select_prompt_multi: "asientos seleccionados",
    compra_continue: "Continuar al pago →",
    // Compra — etapa pago
    compra_back: "← Volver a asientos",
    compra_summary_title: "Resumen de compra",
    compra_route: "Ruta",
    compra_bus_type: "Tipo de bus",
    compra_date: "Fecha",
    compra_passenger: "Pasajero",
    compra_seats: "Asientos",
    compra_discount: "Descuento",
    compra_total: "Total a pagar",
    compra_voucher_title: "Comprobante de pago",
    compra_voucher_desc: "Realiza la transferencia y sube el comprobante. Un oficinista verificará el pago.",
    compra_transfer_data: "Datos de transferencia:",
    compra_upload_label: "Subir comprobante (imagen o PDF)",
    compra_submit: "Confirmar reserva y enviar comprobante",
    compra_submitting: "Procesando reserva...",
    compra_no_discount: "Sin descuento",
    // Compra — etapa confirmación
    compra_confirmed_title: "Reserva confirmada",
    compra_confirmed_desc: "Tu comprobante fue recibido. El oficinista verificará el pago pronto.",
    compra_reservation_num: "Reserva #",
    compra_total_paid: "Total pagado",
    compra_qr_hint: "Muestra este QR al subir al bus",
    compra_print: "Imprimir boleto",
    compra_go_home: "Ir al inicio",
    // Dashboard
    dash_panel: "Panel de gestión",
    dash_welcome: "Bienvenido al panel",
    dash_home: "Inicio",
    dash_cooperative: "Cooperativa",
    dash_buses: "Buses",
    dash_routes: "Rutas",
    dash_users: "Usuarios",
    dash_tickets: "Boletos",
    // Footer
    footer_rights: "Sistema de venta de boletos.",
    footer_made_for: "Hecho para cooperativas de transporte del Ecuador.",
    // Auth
    auth_title: "Bienvenido a BusEcuador",
    auth_subtitle: "Ingresa o crea tu cuenta para comprar boletos.",
    auth_signin: "Ingresar",
    auth_signup: "Crear cuenta",
    auth_email: "Correo",
    auth_password: "Contraseña",
    auth_name: "Nombre completo",
    auth_cedula: "Cédula",
    auth_phone: "Teléfono",
    auth_welcome: "Bienvenido",
    auth_created: "Cuenta creada. Ya puedes ingresar.",
    auth_invalid_credentials: "Credenciales inválidas",
    auth_admin_note: "Las cuentas de oficinista, chofer y administrador se crean desde el panel de administración.",
    auth_err_email: "Correo inválido",
    auth_err_password: "Mínimo 6 caracteres",
    auth_err_name: "Mínimo 3 caracteres",
    auth_err_cedula: "Cédula ecuatoriana inválida",
    auth_err_phone: "Teléfono inválido",
    auth_forgot: "-Recuperar Contraseña-",
    auth_forgot_sent: "El enlace de Recuperacion fue enviado a tu correo.",
    auth_forgot_error: "No se pudo enviar el correo de recuperación.",
    auth_forgot_no_email: "Ingresa su correo porfavor.",
    // Perfil
    perfil_title: "Editar perfil",
    perfil_back: "Volver",
    perfil_email: "Correo electrónico",
    perfil_name: "Nombre completo",
    perfil_name_placeholder: "Tu nombre completo",
    perfil_save: "Guardar",
    perfil_saving: "Guardando...",
    perfil_saved: "Nombre actualizado ✓",
    perfil_name_required: "El nombre es obligatorio",
    perfil_error: "Error al guardar",
    // Reset password
    reset_invalid_title: "Enlace no válido",
    reset_invalid_desc: "Accede a esta página desde el correo de recuperación que te enviamos. El enlace expira en 1 hora.",
    reset_go_home: "Volver al inicio",
    reset_title: "Nueva contraseña",
    reset_subtitle: "Elige una contraseña segura",
    reset_new_password: "Nueva contraseña",
    reset_confirm: "Confirmar contraseña",
    reset_submit: "Confirmar nueva contraseña",
    reset_saving: "Guardando...",
    reset_success: "Contraseña actualizada ✓",
    reset_mismatch: "Las contraseñas no coinciden",
    reset_min: "Mínimo 6 caracteres",
    reset_error: "Error al actualizar la contraseña",
    // Cooperativa
    coop_loading: "Cargando panel...",
    coop_not_found: "No se encontró ninguna cooperativa en la base de datos.",
    coop_error: "Error al cargar estadísticas",
    coop_stat_buses: "Buses activos",
    coop_stat_rutas: "Rutas totales",
    coop_stat_viajes: "Viajes programados",
    coop_stat_reservas: "Reservas pendientes",
    coop_stat_boletos: "Boletos emitidos",
    coop_upcoming: "Próximos viajes programados",
    coop_no_upcoming: "No hay viajes programados próximamente.",
    coop_col_route: "Ruta",
    coop_col_date: "Fecha de salida",
    coop_col_bus: "Bus",
    coop_col_price: "Precio base",
    coop_estado_verificada: "Verificada",
    coop_estado_pendiente: "Pendiente",
    coop_estado_suspendida: "Suspendida",
    coop_page_title: "Cooperativa",
    coop_field_name: "Nombre",
    coop_field_ruc: "RUC",
    coop_field_city: "Ciudad principal",
    coop_field_logo: "Logo",
    coop_field_phone: "Teléfono",
    coop_field_address: "Dirección",
    coop_edit_hint: "Edita estos datos desde Configuración.",
    coop_name_required: "El nombre es obligatorio",
    config_coop_title: "Cooperativa",
    config_coop_desc: "Personaliza la app con los datos de tu cooperativa",
    config_coop_saved: "Cooperativa actualizada ✓",
    config_coop_error: "No se pudo actualizar la cooperativa",
    // Buses
    buses_title: "Gestión de Buses",
    buses_count_singular: "bus registrado",
    buses_count_plural: "buses registrados",
    buses_new: "Nuevo bus",
    buses_search_placeholder: "Buscar por placa, número, chasis o carrocería...",
    buses_loading: "Cargando buses...",
    buses_empty_title: "No hay buses registrados",
    buses_empty_desc: "Haz clic en \"Nuevo bus\" para agregar el primero.",
    buses_active: "Activo",
    buses_inactive: "Inactivo",
    buses_see: "Ver bus",
    buses_no_image: "Sin imagen",
    buses_modal_create: "Registrar nuevo bus",
    buses_modal_edit: "Editar bus",
    buses_label_plate: "Placa *",
    buses_col_name: "Nombre",
    buses_select_brand: "Selecciona una marca",
    buses_plate_invalid: "La placa no es válida en Ecuador (3 letras y 4 números)",
    buses_upload_hint: "Arrastra una imagen aquí o haz clic para subir",
    buses_upload_formats: "PNG, JPG o WEBP",
    buses_upload_uploading: "Subiendo imagen...",
    buses_upload_change: "Cambiar imagen",
    buses_upload_remove: "Quitar imagen",
    buses_upload_error: "No se pudo subir la imagen",
    buses_upload_invalid: "Formato no válido. Usa PNG, JPG o WEBP.",
    buses_label_type: "Tipo",
    buses_label_capacity: "Capacidad (asientos)",
    buses_label_chassis: "Marca del chasis",
    buses_label_body: "Marca de carrocería",
    buses_label_photo: "Foto del bus (opcional)",
    buses_cancel: "Cancelar",
    buses_saving: "Guardando...",
    buses_save_edit: "Guardar cambios",
    buses_save_create: "Registrar bus",
    buses_preview_title: "Vista previa del bus",
    buses_img_error: "No se pudo cargar la imagen.",
    buses_img_error_hint: "Esto suele pasar porque la URL no apunta a un archivo de imagen directo o el sitio externo bloquea la visualización.",
    buses_delete_title: "¿Eliminar este bus?",
    buses_delete_desc: "Esta acción no se puede deshacer. Si el bus tiene viajes o reservas asociadas, considera desactivarlo en su lugar.",
    buses_delete_confirm: "Sí, eliminar",
    buses_plate_required: "La placa es obligatoria",
    buses_updated: "Bus actualizado correctamente ✓",
    buses_created: "Bus registrado correctamente ✓",
    buses_deleted: "Bus eliminado ✓",
    buses_error_load: "Error al cargar buses",
    buses_error_save: "Error al guardar",
    buses_error_delete: "Error al eliminar",
    buses_error_toggle: "Error al cambiar estado",
    buses_type_economico: "Económico",
    buses_type_ejecutivo: "Ejecutivo",
    buses_type_premium: "Premium",
    buses_type_doble_piso: "Doble piso",
    buses_col_num: "N°",
    buses_col_plate: "Placa",
    buses_col_type: "Tipo",
    buses_col_capacity: "Capacidad",
    buses_col_chassis: "Chasis",
    buses_col_body: "Carrocería",
    buses_col_status: "Estado",
    buses_col_photo: "Foto",
    buses_col_actions: "Acciones",
    buses_add_brand_title_chasis: "Agregar marca de chasis",
    buses_add_brand_title_body: "Agregar marca de carrocería",
    buses_add_brand_label: "Nombre de la marca",
    buses_add_brand_placeholder: "Ej: Scania, Marcopolo...",
    buses_add_brand_btn: "Agregar",
    buses_add_brand_success: "Marca agregada correctamente ✓",
    buses_add_brand_empty: "El nombre de la marca no puede estar vacío",
    buses_add_brand_exists: "Esta marca ya existe",
    // Chofer
    chofer_loading: "Cargando sesión...",
    chofer_title: "Panel del Chofer",
    chofer_desc: "Desde aquí podrás revisar tus viajes asignados, validar boletos por QR y registrar ventas presenciales.",
    chofer_tab_trips: "Mis viajes",
    chofer_tab_qr: "Escanear QR",
    chofer_tab_sale: "Venta presencial",
    chofer_stat_assigned: "Viajes asignados",
    chofer_stat_next: "Próximo viaje",
    chofer_stat_no_trips: "Sin viajes",
    chofer_stat_validation: "Validación de boletos",
    chofer_stat_available: "Disponible",
    chofer_trips_title: "Mis viajes asignados",
    chofer_trips_loading: "Cargando viajes...",
    chofer_trips_empty: "No tienes viajes asignados por el momento.",
    chofer_history_title: "Historial de viajes",
    chofer_history_empty: "No tienes viajes completados por el momento.",
    chofer_departure: "Salida:",
    chofer_arrival: "Llegada estimada:",
    chofer_bus_label: "Bus:",
    chofer_bus_unassigned: "No asignado",
    chofer_bus_type: "Tipo de bus:",
    chofer_bus_type_undefined: "No definido",
    chofer_see_passengers: "Ver pasajeros",
    chofer_qr_title: "Validación de asistencia por QR",
    chofer_qr_desc: "Ingresa el código QR del boleto para validar el acceso del pasajero al bus.",
    chofer_camera_starting: "Activando cámara...",
    chofer_camera_stop: "Detener cámara",
    chofer_camera_start: "Activar cámara",
    chofer_camera_manual: "También puedes escribir o corregir manualmente el código QR.",
    chofer_qr_label: "Código QR",
    chofer_search_ticket: "Buscar boleto",
    chofer_clear: "Limpiar",
    chofer_ticket_result: "Resultado del boleto",
    chofer_ticket_code: "Código:",
    chofer_ticket_cannot_validate: "Este boleto no puede validarse nuevamente.",
    chofer_ticket_state: "Estado actual:",
    chofer_ticket_used_at: "usado el",
    chofer_attendance_cannot: "La asistencia no puede validarse.",
    chofer_passenger_data: "Datos del pasajero",
    chofer_trip_seat_data: "Datos del viaje y asiento",
    chofer_field_name: "Nombre:",
    chofer_field_cedula: "Cédula:",
    chofer_field_phone: "Teléfono:",
    chofer_field_email: "Correo:",
    chofer_field_route: "Ruta:",
    chofer_field_departure: "Salida:",
    chofer_field_seat: "Asiento:",
    chofer_field_price: "Precio:",
    chofer_field_reservation: "Reserva:",
    chofer_field_status: "Estado:",
    chofer_field_type: "Tipo:",
    chofer_field_bus: "Bus:",
    chofer_field_base_price: "Precio base:",
    chofer_field_na: "No disponible",
    chofer_validate: "Validar asistencia",
    chofer_sale_title: "Venta presencial durante el viaje",
    chofer_sale_desc: "Registra boletos vendidos por el chofer durante un viaje indirecto en curso.",
    chofer_sale_trip_label: "Viaje asignado",
    chofer_sale_trip_select: "Selecciona un viaje",
    chofer_trip_info: "Información del viaje",
    chofer_start_trip: "Empezar viaje",
    chofer_end_trip: "Terminar viaje",
    chofer_need_in_progress: "Para vender boletos, el viaje debe estar en curso.",
    chofer_direct_no_sale: "Este viaje es directo. No se permite venta presencial durante el recorrido.",
    chofer_sale_data_title: "Datos de la venta",
    chofer_buyer_cedula: "Cédula del comprador",
    chofer_buyer_placeholder: "Ingrese la cédula del comprador",
    chofer_search_buyer: "Buscar comprador",
    chofer_buyer_label: "Comprador:",
    chofer_city_label: "Ciudad / parada",
    chofer_city_select: "Selecciona una ciudad",
    chofer_obs_label: "Observación",
    chofer_obs_placeholder: "Ejemplo: Saliendo de la ciudad",
    chofer_seats_title: "Asientos disponibles",
    chofer_seats_loading: "Cargando asientos...",
    chofer_seats_empty: "No existen asientos disponibles para este viaje.",
    chofer_occupants_title: "Ocupantes por asiento",
    chofer_seat_label: "Asiento",
    chofer_remove: "Quitar",
    chofer_occupant_cedula: "Cédula del ocupante",
    chofer_occupant_placeholder: "Cédula de quien ocupará el asiento",
    chofer_search_occupant: "Buscar ocupante",
    chofer_occupant_label: "Ocupante:",
    chofer_field_age: "Edad:",
    chofer_age_not_registered: "No registrada",
    chofer_disability: "Discapacidad:",
    chofer_discount_label: "Descuento",
    chofer_discount_none: "Ninguno",
    chofer_discount_minor: "Menor",
    chofer_discount_elderly: "Tercera edad",
    chofer_discount_disability: "Discapacidad",
    chofer_seat_price: "Precio asiento",
    chofer_payment_title: "Pago en efectivo",
    chofer_total_pay: "Total a pagar",
    chofer_cash_received: "Efectivo recibido",
    chofer_change: "Cambio",
    chofer_confirm_sale: "Validar venta presencial",
    chofer_sale_success_title: "Venta registrada correctamente",
    chofer_sale_reservation: "Reserva:",
    chofer_sale_total: "Total:",
    chofer_tickets_generated: "Boletos generados y registrados como usados",
    chofer_ticket_passenger: "Pasajero:",
    chofer_ticket_seat: "Asiento:",
    chofer_ticket_qr: "QR:",
    chofer_reserve_pending: "La reserva está pendiente de pago. No se puede validar la asistencia.",
    chofer_reserve_verifying: "El pago de la reserva está en verificación. No se puede validar la asistencia todavía.",
    chofer_reserve_cancelled: "La reserva está cancelada. No se puede validar la asistencia.",
    chofer_reserve_invalid: "La reserva no tiene un estado válido para validar asistencia.",
  },
  en: {
    // Navigation
    nav_search: "Search trips",
    nav_reservations: "My reservations",
    nav_dashboard: "Management panel",
    nav_login: "Log in",
    nav_signup: "Sign up",
    nav_settings: "Settings",
    nav_logout: "Sign out",
    nav_account: "My account",
    // Settings
    config_title: "Settings",
    config_appearance: "Appearance",
    config_dark: "Dark mode",
    config_dark_desc: "Change the platform appearance",
    config_language: "Language",
    config_notifications: "Notifications",
    config_notif_desc: "Receive system alerts",
    config_profile: "Profile",
    config_name: "Full name",
    config_photo: "Profile photo URL",
    config_password: "New password",
    config_confirm_password: "Confirm password",
    config_save: "Save",
    config_saving: "Saving...",
    config_saved: "Changes saved ✓",
    config_password_mismatch: "Passwords do not match",
    config_name_required: "Name is required",
    // Index — Hero
    hero_badge: "✨ Online bus tickets, Ecuador",
    hero_title: "Travel safe and fast across Ecuador",
    hero_subtitle: "Book bus tickets instantly. Secure payment, guaranteed seats and digital ticket on your phone.",
    hero_search_required: "Please fill in all fields to search",
    // Index — Search
    search_origin: "Origin",
    search_origin_placeholder: "Where are you departing from?",
    search_destination: "Destination",
    search_destination_placeholder: "Where are you going?",
    search_date: "Date",
    search_btn: "Search trips",
    // Index — Benefits
    benefits_title: "Why BusEcuador?",
    benefits_subtitle: "A modern booking experience designed for passengers and cooperatives.",
    benefit_seat_title: "Visual seat selection",
    benefit_seat_desc: "Choose your exact seat on an interactive bus map.",
    benefit_pay_title: "Secure payment with validation",
    benefit_pay_desc: "Upload your transfer receipt and an agent will validate it.",
    benefit_qr_title: "Digital ticket with QR",
    benefit_qr_desc: "Keep your ticket on your phone and board showing the QR.",
    benefit_discount_title: "Legal discounts",
    benefit_discount_desc: "We automatically apply minors, senior citizens and disability discounts.",
    benefit_multi_title: "Buy for multiple passengers",
    benefit_multi_desc: "Purchase several seats in a single reservation.",
    benefit_coop_title: "Verified cooperatives",
    benefit_coop_desc: "We work with ANT-authorized operators.",
    // Index — CTA
    cta_title: "Ready for your next trip?",
    cta_subtitle: "Create your free account and start booking tickets in seconds.",
    cta_signup: "Sign up",
    cta_search: "Search trips",
    // Search
    buscar_city: "City",
    buscar_bus_type: "Bus type",
    buscar_all: "All",
    buscar_btn: "Search",
    buscar_empty_title: "No trips found",
    buscar_empty_desc: "Try adjusting the filters or change the date.",
    buscar_discount_applied: "50% discount applied",
    buscar_select_seats: "Choose seats",
    // Purchase — seats step
    compra_loading: "Loading availability...",
    compra_error: "Error",
    compra_trip_selected: "Selected trip",
    compra_price_per_seat: "Price per seat",
    compra_base_price: "base price",
    compra_available: "Available",
    compra_selected: "Selected",
    compra_occupied: "Occupied",
    compra_bus_front: "Front of bus",
    compra_floor1: "Floor 1",
    compra_floor2: "Floor 2 — Premium",
    compra_select_prompt_single: "Select 1 seat to continue",
    compra_select_prompt_multi: "seats selected",
    compra_continue: "Continue to payment →",
    // Purchase — payment step
    compra_back: "← Back to seats",
    compra_summary_title: "Purchase summary",
    compra_route: "Route",
    compra_bus_type: "Bus type",
    compra_date: "Date",
    compra_passenger: "Passenger",
    compra_seats: "Seats",
    compra_discount: "Discount",
    compra_total: "Total to pay",
    compra_voucher_title: "Payment voucher",
    compra_voucher_desc: "Complete the transfer and upload the receipt. An agent will verify the payment.",
    compra_transfer_data: "Transfer details:",
    compra_upload_label: "Upload voucher (image or PDF)",
    compra_submit: "Confirm reservation and send voucher",
    compra_submitting: "Processing reservation...",
    compra_no_discount: "No discount",
    // Purchase — confirmation step
    compra_confirmed_title: "Reservation confirmed",
    compra_confirmed_desc: "Your voucher was received. The agent will verify the payment soon.",
    compra_reservation_num: "Reservation #",
    compra_total_paid: "Total paid",
    compra_qr_hint: "Show this QR when boarding the bus",
    compra_print: "Print ticket",
    compra_go_home: "Go to home",
    // Dashboard
    dash_panel: "Management panel",
    dash_welcome: "Welcome to the panel",
    dash_home: "Home",
    dash_cooperative: "Cooperative",
    dash_buses: "Buses",
    dash_routes: "Routes",
    dash_users: "Users",
    dash_tickets: "Tickets",
    // Footer
    footer_rights: "Bus ticket sales system.",
    footer_made_for: "Built for Ecuador's transport cooperatives.",
    // Auth
    auth_title: "Welcome to BusEcuador",
    auth_subtitle: "Log in or create your account to buy tickets.",
    auth_signin: "Log in",
    auth_signup: "Sign up",
    auth_email: "Email",
    auth_password: "Password",
    auth_name: "Full name",
    auth_cedula: "ID",
    auth_phone: "Phone",
    auth_welcome: "Welcome",
    auth_created: "Account created. You can now log in.",
    auth_invalid_credentials: "Invalid credentials",
    auth_admin_note: "Staff, driver and admin accounts are created from the management panel.",
    auth_err_email: "Invalid email",
    auth_err_password: "Minimum 6 characters",
    auth_err_name: "Minimum 3 characters",
    auth_err_cedula: "Invalid Ecuadorian ID",
    auth_err_phone: "Invalid phone",
    auth_forgot: "Forgot your password?",
    auth_forgot_sent: "Check your email to reset your password.",
    auth_forgot_error: "Could not send the recovery email.",
    auth_forgot_no_email: "Enter your email first.",
    // Perfil
    perfil_title: "Edit profile",
    perfil_back: "Back",
    perfil_email: "Email address",
    perfil_name: "Full name",
    perfil_name_placeholder: "Your full name",
    perfil_save: "Save",
    perfil_saving: "Saving...",
    perfil_saved: "Name updated ✓",
    perfil_name_required: "Name is required",
    perfil_error: "Error saving",
    // Reset password
    reset_invalid_title: "Invalid link",
    reset_invalid_desc: "Access this page from the recovery email we sent you. The link expires in 1 hour.",
    reset_go_home: "Go to home",
    reset_title: "New password",
    reset_subtitle: "Choose a secure password",
    reset_new_password: "New password",
    reset_confirm: "Confirm password",
    reset_submit: "Set new password",
    reset_saving: "Saving...",
    reset_success: "Password updated ✓",
    reset_mismatch: "Passwords do not match",
    reset_min: "Minimum 6 characters",
    reset_error: "Error updating password",
    // Cooperativa
    coop_loading: "Loading panel...",
    coop_not_found: "No cooperative found in the database.",
    coop_error: "Error loading statistics",
    coop_stat_buses: "Active buses",
    coop_stat_rutas: "Total routes",
    coop_stat_viajes: "Scheduled trips",
    coop_stat_reservas: "Pending reservations",
    coop_stat_boletos: "Tickets issued",
    coop_upcoming: "Upcoming scheduled trips",
    coop_no_upcoming: "No trips scheduled soon.",
    coop_col_route: "Route",
    coop_col_date: "Departure date",
    coop_col_bus: "Bus",
    coop_col_price: "Base price",
    coop_estado_verificada: "Verified",
    coop_estado_pendiente: "Pending",
    coop_estado_suspendida: "Suspended",
    coop_page_title: "Cooperative",
    coop_field_name: "Name",
    coop_field_ruc: "Tax ID (RUC)",
    coop_field_city: "Main city",
    coop_field_logo: "Logo",
    coop_field_phone: "Phone",
    coop_field_address: "Address",
    coop_edit_hint: "Edit these details from Settings.",
    coop_name_required: "Name is required",
    config_coop_title: "Cooperative",
    config_coop_desc: "Customize the app with your cooperative's details",
    config_coop_saved: "Cooperative updated ✓",
    config_coop_error: "Could not update the cooperative",
    // Buses
    buses_title: "Bus Management",
    buses_count_singular: "registered bus",
    buses_count_plural: "registered buses",
    buses_new: "New bus",
    buses_search_placeholder: "Search by plate, number, chassis or bodywork...",
    buses_loading: "Loading buses...",
    buses_empty_title: "No buses registered",
    buses_empty_desc: "Click \"New bus\" to add the first one.",
    buses_active: "Active",
    buses_inactive: "Inactive",
    buses_see: "View bus",
    buses_no_image: "No image",
    buses_modal_create: "Register new bus",
    buses_modal_edit: "Edit bus",
    buses_label_plate: "Plate *",
    buses_col_name: "Name",
    buses_select_brand: "Select a brand",
    buses_plate_invalid: "The plate is not valid in Ecuador (3 letters and 4 numbers)",
    buses_upload_hint: "Drag an image here or click to upload",
    buses_upload_formats: "PNG, JPG or WEBP",
    buses_upload_uploading: "Uploading image...",
    buses_upload_change: "Change image",
    buses_upload_remove: "Remove image",
    buses_upload_error: "Could not upload the image",
    buses_upload_invalid: "Invalid format. Use PNG, JPG or WEBP.",
    buses_label_type: "Type",
    buses_label_capacity: "Capacity (seats)",
    buses_label_chassis: "Chassis brand",
    buses_label_body: "Bodywork brand",
    buses_label_photo: "Bus photo (optional)",
    buses_cancel: "Cancel",
    buses_saving: "Saving...",
    buses_save_edit: "Save changes",
    buses_save_create: "Register bus",
    buses_preview_title: "Bus preview",
    buses_img_error: "Could not load image.",
    buses_img_error_hint: "This usually happens because the URL doesn't point to a direct image file or the external site blocks display.",
    buses_delete_title: "Delete this bus?",
    buses_delete_desc: "This action cannot be undone. If the bus has associated trips or reservations, consider deactivating it instead.",
    buses_delete_confirm: "Yes, delete",
    buses_plate_required: "Plate is required",
    buses_updated: "Bus updated successfully ✓",
    buses_created: "Bus registered successfully ✓",
    buses_deleted: "Bus deleted ✓",
    buses_error_load: "Error loading buses",
    buses_error_save: "Error saving",
    buses_error_delete: "Error deleting",
    buses_error_toggle: "Error changing status",
    buses_type_economico: "Economy",
    buses_type_ejecutivo: "Executive",
    buses_type_premium: "Premium",
    buses_type_doble_piso: "Double decker",
    buses_col_num: "N°",
    buses_col_plate: "Plate",
    buses_col_type: "Type",
    buses_col_capacity: "Capacity",
    buses_col_chassis: "Chassis",
    buses_col_body: "Bodywork",
    buses_col_status: "Status",
    buses_col_photo: "Photo",
    buses_col_actions: "Actions",
    buses_add_brand_title_chasis: "Add chassis brand",
    buses_add_brand_title_body: "Add bodywork brand",
    buses_add_brand_label: "Brand name",
    buses_add_brand_placeholder: "e.g. Scania, Marcopolo...",
    buses_add_brand_btn: "Add",
    buses_add_brand_success: "Brand added successfully ✓",
    buses_add_brand_empty: "Brand name cannot be empty",
    buses_add_brand_exists: "This brand already exists",
    // Chofer
    chofer_loading: "Loading session...",
    chofer_title: "Driver Panel",
    chofer_desc: "From here you can review your assigned trips, validate tickets by QR and register in-person sales.",
    chofer_tab_trips: "My trips",
    chofer_tab_qr: "Scan QR",
    chofer_tab_sale: "In-person sale",
    chofer_stat_assigned: "Assigned trips",
    chofer_stat_next: "Next trip",
    chofer_stat_no_trips: "No trips",
    chofer_stat_validation: "Ticket validation",
    chofer_stat_available: "Available",
    chofer_trips_title: "My assigned trips",
    chofer_trips_loading: "Loading trips...",
    chofer_trips_empty: "You have no trips in progress at the moment.",
    chofer_history_title: "Trip history",
    chofer_history_empty: "You have no completed trips at the moment.",
    chofer_departure: "Departure:",
    chofer_arrival: "Estimated arrival:",
    chofer_bus_label: "Bus:",
    chofer_bus_unassigned: "Not assigned",
    chofer_bus_type: "Bus type:",
    chofer_bus_type_undefined: "Not defined",
    chofer_see_passengers: "See passengers",
    chofer_qr_title: "QR attendance validation",
    chofer_qr_desc: "Enter the ticket QR code to validate passenger access to the bus.",
    chofer_camera_starting: "Starting camera...",
    chofer_camera_stop: "Stop camera",
    chofer_camera_start: "Start camera",
    chofer_camera_manual: "You can also manually enter or correct the QR code.",
    chofer_qr_label: "QR Code",
    chofer_search_ticket: "Search ticket",
    chofer_clear: "Clear",
    chofer_ticket_result: "Ticket result",
    chofer_ticket_code: "Code:",
    chofer_ticket_cannot_validate: "This ticket cannot be validated again.",
    chofer_ticket_state: "Current status:",
    chofer_ticket_used_at: "used on",
    chofer_attendance_cannot: "Attendance cannot be validated.",
    chofer_passenger_data: "Passenger data",
    chofer_trip_seat_data: "Trip and seat data",
    chofer_field_name: "Name:",
    chofer_field_cedula: "ID:",
    chofer_field_phone: "Phone:",
    chofer_field_email: "Email:",
    chofer_field_route: "Route:",
    chofer_field_departure: "Departure:",
    chofer_field_seat: "Seat:",
    chofer_field_price: "Price:",
    chofer_field_reservation: "Reservation:",
    chofer_field_status: "Status:",
    chofer_field_type: "Type:",
    chofer_field_bus: "Bus:",
    chofer_field_base_price: "Base price:",
    chofer_field_na: "Not available",
    chofer_validate: "Validate attendance",
    chofer_sale_title: "In-person sale during trip",
    chofer_sale_desc: "Record tickets sold by the driver during an ongoing indirect trip.",
    chofer_sale_trip_label: "Assigned trip",
    chofer_sale_trip_select: "Select a trip",
    chofer_trip_info: "Trip information",
    chofer_start_trip: "Start trip",
    chofer_end_trip: "End trip",
    chofer_need_in_progress: "To sell tickets, the trip must be in progress.",
    chofer_direct_no_sale: "This trip is direct. In-person sales are not allowed during the journey.",
    chofer_sale_data_title: "Sale data",
    chofer_buyer_cedula: "Buyer ID",
    chofer_buyer_placeholder: "Enter buyer's ID",
    chofer_search_buyer: "Search buyer",
    chofer_buyer_label: "Buyer:",
    chofer_city_label: "City / stop",
    chofer_city_select: "Select a city",
    chofer_obs_label: "Observation",
    chofer_obs_placeholder: "Example: Leaving the city",
    chofer_seats_title: "Available seats",
    chofer_seats_loading: "Loading seats...",
    chofer_seats_empty: "No available seats for this trip.",
    chofer_occupants_title: "Occupants per seat",
    chofer_seat_label: "Seat",
    chofer_remove: "Remove",
    chofer_occupant_cedula: "Occupant ID",
    chofer_occupant_placeholder: "ID of the seat occupant",
    chofer_search_occupant: "Search occupant",
    chofer_occupant_label: "Occupant:",
    chofer_field_age: "Age:",
    chofer_age_not_registered: "Not registered",
    chofer_disability: "Disability:",
    chofer_discount_label: "Discount",
    chofer_discount_none: "None",
    chofer_discount_minor: "Minor",
    chofer_discount_elderly: "Senior",
    chofer_discount_disability: "Disability",
    chofer_seat_price: "Seat price",
    chofer_payment_title: "Cash payment",
    chofer_total_pay: "Total to pay",
    chofer_cash_received: "Cash received",
    chofer_change: "Change",
    chofer_confirm_sale: "Confirm in-person sale",
    chofer_sale_success_title: "Sale registered successfully",
    chofer_sale_reservation: "Reservation:",
    chofer_sale_total: "Total:",
    chofer_tickets_generated: "Tickets generated and registered as used",
    chofer_ticket_passenger: "Passenger:",
    chofer_ticket_seat: "Seat:",
    chofer_ticket_qr: "QR:",
    chofer_reserve_pending: "The reservation is pending payment. Attendance cannot be validated.",
    chofer_reserve_verifying: "The reservation payment is being verified. Attendance cannot be validated yet.",
    chofer_reserve_cancelled: "The reservation is cancelled. Attendance cannot be validated.",
    chofer_reserve_invalid: "The reservation does not have a valid status to validate attendance.",
  },
} as const;

export type TKey = keyof typeof T["es"];

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: TKey) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(
    () => (localStorage.getItem("lang") as Lang) ?? "es"
  );

  const setLang = (l: Lang) => {
    localStorage.setItem("lang", l);
    setLangState(l);
  };

  const t = (key: TKey): string => T[lang][key];

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLang debe usarse dentro de LanguageProvider");
  return ctx;
}
